In [1]:
import pandas as pd
df= pd.read_excel("C:/Users/sithu/Desktop/BI/Projects/full/Ecommerce Sales Data.xlsx")

In [2]:
df.head(10)

,Order ID,Order Date,Customer Name,Region,City,Category,Sub-Category,Product Name,Quantity,Unit Price,Discount,Sales,Profit,Payment Mode
0,10001,2024-10-19,Kashvi Varty,South,Bangalore,Books,Non-Fiction,Non-Fiction Ipsum,2,36294,5,68958.60,10525.09,Debit Card
1,10002,2025-08-30,Advik Desai,North,Delhi,Groceries,Rice,Rice Nemo,1,42165,20,33732.00,6299.66,Debit Card
2,10003,2023-11-04,Rhea Kalla,East,Patna,Kitchen,Juicer,Juicer Odio,4,64876,20,207603.20,19850.27,Credit Card
3,10004,2025-05-23,Anika Sen,East,Kolkata,Groceries,Oil,Oil Doloribus,5,37320,15,158610.00,36311.02,UPI
4,10005,2025-01-19,Akarsh Kaul,West,Pune,Clothing,Kids Wear,Kids Wear Quo,1,50037,10,45033.30,9050.04,Debit Card
5,10006,2025-04-06,Vardaniya Jayaraman,West,Pune,Furniture,Chair,Chair Assumenda,5,40287,15,171219.75,23722.84,Credit Card
6,10007,2023-10-13,Drishya Khare,West,Mumbai,Clothing,Accessories,Accessories Minima,2,3636,5,6908.40,680.26,Debit Card
7,10008,2025-08-17,Misha Dua,North,Lucknow,Books,Biography,Biography Vel,1,15885,10,14296.50,1289.03,Debit Card
8,10009,2025-03-07,Arhaan Vala,North,Jaipur,Groceries,Spices,Spices Expedita,1,40834,20,32667.20,3700.89,Credit Card
9,10010,2024-12-02,Lavanya Hayer,West,Goa,Kitchen,Juicer,Juicer Voluptatibus,2,16686,15,28366.20,5703.09,UPI

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order ID       5000 non-null   int64
 1   Order Date     5000 non-null   datetime64[ns]
 2   Customer Name  5000 non-null   object
 3   Region         5000 non-null   object
 4   City           5000 non-null   object
 5   Category       5000 non-null   object
 6   Sub-Category   5000 non-null   object
 7   Product Name   5000 non-null   object
 8   Quantity       5000 non-null   int64
 9   Unit Price     5000 non-null   int64
 10  Discount       5000 non-null   int64
 11  Sales          5000 non-null   float64
 12  Profit         5000 non-null   float64
 13  Payment Mode   5000 non-null   object
dtypes: datetime64[ns](1), float64(2), int64(4), object(7)
memory usage: 547.0+ KB

In [4]:
df.describe()

,Order ID,Order Date,Quantity,Unit Price,Discount,Sales,Profit
count,5000.000000,5000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,12500.500000,2024-09-30 18:58:27.840000,2.992600,39760.904600,10.051000,106733.204870,15941.746982
min,10001.000000,2023-10-04 00:00:00,1.000000,222.000000,0.000000,264.100000,19.120000
25%,11250.750000,2024-04-05 00:00:00,2.000000,20312.250000,5.000000,39766.537500,4892.295000
50%,12500.500000,2024-09-29 00:00:00,3.000000,39459.500000,10.000000,83080.325000,11108.525000
75%,13750.250000,2025-03-30 00:00:00,4.000000,59721.750000,15.000000,156968.587500,22467.987500
max,15000.000000,2025-10-03 00:00:00,5.000000,79998.000000,20.000000,398485.000000,89688.440000
std,1443.520003,NaN,1.413133,22831.783946,7.084662,85108.208202,14897.684916

In [5]:
df.isnull().sum()

Order ID         0
Order Date       0
Customer Name    0
Region           0
City             0
Category         0
Sub-Category     0
Product Name     0
Quantity         0
Unit Price       0
Discount         0
Sales            0
Profit           0
Payment Mode     0
dtype: int64

In [7]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')
df = df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})
print(df)

      order_id order_date      customer_name region       city     category  \
0        10001 2024-10-19       Kashvi Varty  South  Bangalore        Books
1        10002 2025-08-30        Advik Desai  North      Delhi    Groceries
2        10003 2023-11-04         Rhea Kalla   East      Patna      Kitchen
3        10004 2025-05-23          Anika Sen   East    Kolkata    Groceries
4        10005 2025-01-19        Akarsh Kaul   West       Pune     Clothing
...        ...        ...                ...    ...        ...          ...
4995     14996 2024-06-25   Nishith Kulkarni   East    Kolkata        Books
4996     14997 2024-12-22      Aaina Chander  North     Jaipur         Toys
4997     14998 2025-04-15       Dhanush Gara  South  Bangalore       Beauty
4998     14999 2024-07-08  Divyansh Malhotra   East    Kolkata  Electronics
4999     15000 2024-02-04       Aarush Walla   West        Goa     Clothing

     sub-category         product_name  quantity  unit_price  discount  \
0     Non-Fiction    Non-Fiction Ipsum         2       36294         5
1            Rice            Rice Nemo         1       42165        20
2          Juicer          Juicer Odio         4       64876        20
3             Oil        Oil Doloribus         5       37320        15
4       Kids Wear        Kids Wear Quo         1       50037        10
...           ...                  ...       ...         ...       ...
4995      Fiction    Fiction Veritatis         3       60671         0
4996         Doll           Doll Nulla         5       70048         0
4997     Lipstick       Lipstick Eaque         1       42162        15
4998   Smartwatch  Smartwatch Adipisci         4       13568        10
4999    Kids Wear   Kids Wear Repellat         1       76762        10

         sales    profit payment_mode
0      68958.6  10525.09   Debit Card
1      33732.0   6299.66   Debit Card
2     207603.2  19850.27  Credit Card
3     158610.0  36311.02          UPI
4      45033.3   9050.04   Debit Card
...        ...       ...          ...
4995  182013.0  11853.15   Debit Card
4996  350240.0  31237.23  Credit Card
4997   35837.7   7827.50   Debit Card
4998   48844.8   6603.86  Credit Card
4999   69085.8   5785.85  Net Banking

[5000 rows x 14 columns]

In [16]:
pip install pymysql sqlalchemy

Defaulting to user installation because normal site-packages is not writeable
Collecting pymysql
  Downloading pymysql-1.1.2-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: sqlalchemy in c:\programdata\anaconda3\lib\site-packages (2.0.39)
Requirement already satisfied: greenlet!=0.4.17 in c:\programdata\anaconda3\lib\site-packages (from sqlalchemy) (3.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\programdata\anaconda3\lib\site-packages (from sqlalchemy) (4.12.2)
Downloading pymysql-1.1.2-py3-none-any.whl (45 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.1.2
Note: you may need to restart the kernel to use updated packages.

In [8]:
import pandas as pd
from sqlalchemy import create_engine

username = "root"
password = "Sithu%40123"  # encode special chars
host = "127.0.0.1"        # or "localhost"
port = "3306"
database = "ecommerce_sales_data"  # must exist

engine = create_engine(f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}")


# Write DataFrame to MySQL
table_name = "Sales"
df.to_sql(table_name, engine, if_exists="replace", index=False)

# Read back sample
sample_df = pd.read_sql(f"SELECT * FROM {table_name} LIMIT 5;", engine)
print(sample_df)

   order_id order_date customer_name region       city   category  \
0     10001 2024-10-19  Kashvi Varty  South  Bangalore      Books
1     10002 2025-08-30   Advik Desai  North      Delhi  Groceries
2     10003 2023-11-04    Rhea Kalla   East      Patna    Kitchen
3     10004 2025-05-23     Anika Sen   East    Kolkata  Groceries
4     10005 2025-01-19   Akarsh Kaul   West       Pune   Clothing

  sub-category       product_name  quantity  unit_price  discount     sales  \
0  Non-Fiction  Non-Fiction Ipsum         2       36294         5   68958.6
1         Rice          Rice Nemo         1       42165        20   33732.0
2       Juicer        Juicer Odio         4       64876        20  207603.2
3          Oil      Oil Doloribus         5       37320        15  158610.0
4    Kids Wear      Kids Wear Quo         1       50037        10   45033.3

     profit payment_mode
0  10525.09   Debit Card
1   6299.66   Debit Card
2  19850.27  Credit Card
3  36311.02          UPI
4   9050.04   Debit Card

C:\Users\sithu\AppData\Local\Temp\ipykernel_27724\2528855071.py:15: UserWarning: The provided table name 'Sales' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  df.to_sql(table_name, engine, if_exists="replace", index=False)